### ISSUE TITLE
Portfolio 9 - Suggestions

### ISSUE THREAD

**Issue by rrustia** [luayghazwan/Portfolio#12]
Hello, these are my observations. I couldn't see many parts that need improvement(your code organization looks much cleaner than mine!).

1. I'm thinking of replacing all 'var' instances with 'let' to make use of one of our class topic.
2. On the JSON file, I think it would be more readable if each opening '{' is on its own line. 
3. Also maybe more comments on the articleView.js file(like on the fetchall and onclick function) to let other people understand it a little easier. (this is something I need to do also)

All in all I think your code has a great format.

**Comment by luyounus** [comment]
Thank you Ronel for the tips. I used your suggestions to make my code look cleaner.
